Issue/v4/983 implement documents news endpoints
bedita/bedita pull request #1071
Opened 2017-02-06 11:58 UTC by stefanorosanelli

This PR solves #983 

 * CRUD actions on `/documents`, `/news` and other object type endpoints are implemented

 * `/home` response updated with new dynamic endpoints

2017-02-06 15:35 UTC, batopa requested changes

2017-02-06 15:35 UTC, batopa commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        $object->type = $this->request->data('type');
I think that here is required a check on consistency between `data('type')` and the endpoint used. For example I could send
```http
POST /documents

{
    "type": "users",
    "attributes": {
        "title": "New document"
    }
}
```

A `400 Bad Request` should be expected (missing unit test too)

2017-02-06 15:35 UTC, batopa commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        if ($this->request->data('id') != $id) {
Same validation data on `type` shown above is required

2017-02-06 15:35 UTC, batopa commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        $object = $this->Objects->get($id, [
Missing conditions on object type if specific endpoint is used and 404 Not Found if missing the object to delete

2017-02-07 10:22 UTC, stefanorosanelli commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        $object->type = $this->request->data('type');
Right, type check added

2017-02-07 10:22 UTC, stefanorosanelli commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        if ($this->request->data('id') != $id) {
Type check added in edit

2017-02-07 10:24 UTC, stefanorosanelli commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        $object = $this->Objects->get($id, [
Type check added here too.
404 not found is handled directly in `$this->Objects->get()` call
Added 404 tests for delete and edit actions

2017-02-07 15:38 UTC, batopa approved these changes

2017-02-08 09:19 UTC, merged