Admin endpoint
bedita/bedita pull request #1293
Opened 2017-07-18 13:50 UTC by stefanorosanelli

This PR solves #1292 

First minimal implementation of `/admin` endpoint 

Through `/admin/applications` and usual POST, GET, PATCH, DELETE methods `applications` are managed.

2017-07-19 09:17 UTC, didoda commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +     *
missing `@param $type`

2017-07-19 09:19 UTC, didoda approved these changes

2017-07-19 10:56 UTC, stefanorosanelli commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +     *
:+1:      
done!

2017-07-28 11:44 UTC, batopa requested changes

2017-07-28 11:44 UTC, batopa commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +     */
Missing `@return`

2017-07-28 11:44 UTC, batopa commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +     *
Missing `@return` too

2017-07-28 11:44 UTC, batopa commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +        $result = json_decode((string)$this->_response->getBody(), true);
unused `$result` variable. Missing a test on it?

2017-07-28 11:44 UTC, batopa commented on plugins/BEdita/API/tests/TestCase/Controller/AdminControllerTest.php
> +        $result = json_decode((string)$this->_response->getBody(), true);
`$result` not used

2017-07-28 11:44 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiAdminTraitTest.php
> +use BEdita\Core\Utility\JsonApiSerializable;
Useless `use` statement for `JsonApiSerializable` and `Hash`

2017-07-28 13:58 UTC, stefanorosanelli commented on plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiAdminTraitTest.php
> +use BEdita\Core\Utility\JsonApiSerializable;
done

2017-07-28 13:58 UTC, stefanorosanelli commented on plugins/BEdita/API/tests/TestCase/Controller/AdminControllerTest.php
> +        $result = json_decode((string)$this->_response->getBody(), true);
done

2017-07-28 14:00 UTC, stefanorosanelli commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +        $result = json_decode((string)$this->_response->getBody(), true);
removed for now

a detailed view test would be preferable, maybe not in IntegrationTest?

2017-07-28 14:00 UTC, stefanorosanelli commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +     */
added

2017-07-28 14:01 UTC, stefanorosanelli commented on plugins/BEdita/API/tests/IntegrationTest/AdminResourcesTest.php
> +     *
added

2017-07-28 15:24 UTC, fquffio commented
I like the approach to have a single controller manage multiple resources, however I don't really like having a single `AdminController`. `admin/` prefix sounds like something that might become really complex and "wide".

Rather than a single `AdminController` I'd have a `Controller/Admin` namespace with a `ResourcesController` in it. Routes would then be connected using a [prefix](https://book.cakephp.org/3.0/en/development/routing.html#prefix-routing).

This is not blocking: we could switch to this approach in the future if and when we'll actually need this.

2017-08-03 13:51 UTC, stefanorosanelli commented
Agreed, and `/admin` prefix and a `Controller\Admin` namespace are both good ideas.

We could to it, among with other necessary improvements, in one or more new issues.

2017-08-04 09:47 UTC, batopa approved these changes

2017-08-04 09:47 UTC, merged