OTP auth flow #1535
bedita/bedita pull request #1537
Opened 2018-09-13 15:25 UTC by stefanorosanelli

This PR solves #1535 

* a new `user_tokens` table was created to save one time passwords as well as `refresh` tokens and other items regarding user auth
* a new `OTPAuthenticate` class to handle OTP Request and OTP Access flow as described in https://github.com/orgs/bedita/teams/core/discussions/9
  + client authorization codes are generated via UUID
  + secret tokens are generated as random numeric strings as default, but custom generatos can be defined
* `LoginController::login()` was modified in order to handle this new flow in `POST /auth` as well

2018-10-01 10:26 UTC, fquffio requested changes

2018-10-01 10:26 UTC, fquffio commented on plugins/BEdita/API/src/Auth/OTPAuthenticate.php
> +        return $res;
This is cryptographically insecure. Maybe it's not a big deal, but it would be enough to replace this method with something like this:

```php
return sprintf('%06d', hexdec(bin2hex(Security::randomBytes(2))));
```

2018-10-01 10:26 UTC, fquffio commented on plugins/BEdita/Core/config/Migrations/20180911142444_AddUserTokensTable.php
> +                'values' => ['otp', 'refresh', 'recovery', '2fa', 'access'],
Enforcing this constraint on the database seems a bit hardcore: if we wan to add new types we need to bake a migration. I'd enforce it only on the application level, and leave this a `VARCHAR(255)`.

2018-10-01 10:26 UTC, fquffio commented on plugins/BEdita/Core/config/Migrations/20180911142444_AddUserTokensTable.php
> +            )
Two more indexes could be useful: `expires` and `used`. I would expect many queries built this way:

```sql
SELECT * FROM user_tokens
  WHERE
    /* conditions on user_id, application_id, token_type, … */
    AND used IS NULL -- !!
    AND expires > NOW() --!!
    LIMIT 1;
```

2018-10-01 10:26 UTC, fquffio commented on plugins/BEdita/Core/src/Model/Table/UserTokensTable.php
> +            ->requirePresence('token_type', 'create')
I'd validate the type too:

```php
$validator
  // ...
  ->inList('token_type', ['foo', 'bar'])
  // ...
```

2018-10-03 07:29 UTC, stefanorosanelli commented on plugins/BEdita/API/src/Auth/OTPAuthenticate.php
> +        return $res;
I know didn't want to introduce cryptographic algorithm, but I'd use same used for passwords.

2018-10-03 07:30 UTC, stefanorosanelli commented on plugins/BEdita/Core/config/Migrations/20180911142444_AddUserTokensTable.php
> +            )
Still not sure how much we'll use `used`, but I'll add both

2018-10-03 07:31 UTC, stefanorosanelli commented on plugins/BEdita/Core/src/Model/Table/UserTokensTable.php
> +            ->requirePresence('token_type', 'create')
Ok

2018-10-03 15:44 UTC, fquffio commented on plugins/BEdita/Core/config/Migrations/20180911142444_AddUserTokensTable.php
> +            )
Recovery tokens for MFA, for instance, should definitely be kept in this table, for security audits.

2018-10-03 15:45 UTC, fquffio approved these changes

2018-10-05 08:37 UTC, batopa reviewed
ok for me! Just a minor comment

2018-10-05 08:37 UTC, batopa commented on plugins/BEdita/API/src/Auth/OTPAuthenticate.php
> +        if (empty($request->getData('authorization_code')) || empty($request->getData('token'))) {
[minor] I would move this check before of  `_findUser()` to avoid useless query on db if missing required params.

2018-10-05 08:57 UTC, batopa approved these changes

2018-10-05 10:44 UTC, merged