`profiles.email` non unique index
bedita/bedita pull request #1539
Opened 2018-09-18 15:42 UTC by stefanorosanelli

This PR fixes some problems related to `profiles.email` uniqueness: it is now a `normal` index.

2018-09-19 10:12 UTC, batopa approved these changes

2018-09-20 07:07 UTC, batopa requested changes
If it's possible I would add an application rules in `UsersTable` that check the email uniqueness.

Indeed the validation layer rules are applied only when `Table::newEntity()` or `Table::patchEntity()` are used but doing

```php
$table = \Cake\ORM\TableRegistry::init('Users)`;
$user = $table->newEntity();
$user->email = 'g.supporto@channelweb.it';
$table->save($user);
```
will skip the validation rules but not the application rules that are intended to comparing data against the existing state of the application.

https://book.cakephp.org/3.0/en/orm/validation.html#validation-vs-application-rules

2018-09-20 07:07 UTC, batopa commented on plugins/BEdita/Core/src/Model/Table/UsersTable.php
> +    public function validateUniqueEmail($value)
I think we could use the CakePHP core validation rule `Table::validateUnique()`

2018-09-20 07:48 UTC, stefanorosanelli commented on plugins/BEdita/Core/src/Model/Table/UsersTable.php
> +    public function validateUniqueEmail($value)
done

2018-09-20 08:02 UTC, batopa approved these changes

2018-09-20 09:47 UTC, merged