WIP: custom types from config for multimedia module
bedita/bedita pull request #1567
Opened 2018-11-26 08:40 UTC by didoda

This PR provides the possibility to customize the types to handle in multimedia module, using a configuration.
For instance:
```
// default: 'b_e_file', 'image', 'audio', 'video', 'application'
$config['multimedia']['types'] = array('audio', 'image', 'video');
```

2018-11-26 09:10 UTC, stefanorosanelli commented
This information should be read from API using something like:
```

2018-11-26 11:05 UTC, fquffio approved these changes
What if we access a disabled media type directly?

Imagine we have disabled video and object 123 is a video: `/multimedia/view/123` would result in an error?

2018-11-26 11:05 UTC, fquffio commented on bedita-app/controllers/modules/multimedia_controller.php
> +        foreach ($mime as $modelMyme => $data) {
[minor] Typo: `modelMime`. 😄

2018-11-26 11:24 UTC, didoda commented
Good point, @fquffio We should handle `view/:not_allowed_item_id` case

2018-11-26 12:00 UTC, fquffio approved these changes

2018-11-28 11:39 UTC, batopa requested changes

2018-11-28 11:39 UTC, batopa commented on bedita-app/controllers/modules/multimedia_controller.php
> +    protected $object_types = array('application', 'audio', 'b_e_file', 'image', 'video');
should be `$objectTypes`

2018-11-28 11:43 UTC, batopa approved these changes

2018-11-28 11:46 UTC, merged