Issue/v4/1638 object categories
bedita/bedita pull request #1639
Opened 2019-11-26 10:08 UTC by stefanorosanelli

This PR fixes #1638

2019-12-09 12:33 UTC, batopa commented
@stefanorosanelli there are some conflicts, please can you resolve them?

2019-12-09 13:04 UTC, stefanorosanelli commented
> @stefanorosanelli there are some conflicts, please can you resolve them?

Should be ok now

2019-12-23 11:25 UTC, didoda approved these changes

2020-01-03 10:30 UTC, batopa requested changes
I think a better implementation could be done having two Tables and Entities i.e. `CategoriesTable`, `TagsTable`, `Category` and `Tag`.

Every table could use a common `CategoriesTrait` that implements common functions while the single tables should specify their peculiarity.

For example for `TagsTable` we can avoid to have

```php
$this->belongsTo('ObjectTypes', [
    'foreignKey' => 'object_type_id',
    'className' => 'BEdita/Core.ObjectTypes'
]);
$this->belongsTo('ParentCategories', [
    'className' => 'BEdita/Core.Categories',
    'foreignKey' => 'parent_id'
]);
$this->hasMany('ChildCategories', [
    'className' => 'BEdita/Core.Categories',
    'foreignKey' => 'parent_id'
]);
$this->addBehavior('Tree', [
    'left' => 'tree_left',
    'right' => 'tree_right',
]);
```

Every Table should implement a `beforeFind()`method to add the condition on `object_type_id` (NULL OR NOT NULL).

`findEnabledTags()` and `findEnabledCategories()` could be simplified as

```
protected function findEnabled(Query $query)
{
    return $query->where([
        $this->aliasField('enabled') => true,
    ]);
}
```

And also `findCategoriesIds()` and `findTagsIds()` can be simplified and having the same name.

The `Tag` and `Category` entities will be equal but we could easily customize them in the future.

In this way I think its more clear to use tag and categories. For example

```php
// every time I want tags I know I have to use TagsTable 
// instead of use CategoriesTable with specific conditions

$categories = TableRegistry::getTableLocator()->get('Categories')->find('enabled');
$tags = TableRegistry::getTableLocator()->get('Tags')->find('enabled');
```

The associations in `ObjectsTable` will change slighlty

```php
$this->belongsToMany('Categories', [
    'className' => 'BEdita/Core.Categories',
    'through' => 'BEdita/Core.ObjectCategories',
    'foreignKey' => 'object_id',
    'targetForeignKey' => 'category_id',
    'finder' => 'enabled',
    'cascadeCallbacks' => true,
]);
$this->belongsToMany('Tags', [
    'className' => 'BEdita/Core.Tags',
    'through' => 'BEdita/Core.ObjectCategories',
    'foreignKey' => 'object_id',
    'targetForeignKey' => 'category_id',
    'finder' => 'enabled',
    'cascadeCallbacks' => true,
]);
```

and some changes will have to done in `CategoriesBehavior`.

What do you think about it? Do you think it's worth it?

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/API/tests/IntegrationTest/TagsCategoriesTest.php
> +// pr($result);
remove comment

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/API/tests/IntegrationTest/TagsCategoriesTest.php
> +// pr($result);
remove comment

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Behavior/CategoriesBehaviorTest.php
> +
remove empty line here

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Behavior/CategoriesBehaviorTest.php
> +
remove empty line here

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Behavior/CategoriesBehaviorTest.php
> +     * Test correct save of custom properties.
The comment here is wrong... I suppose :smile:

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectCategoriesTableTest.php
> +        $this->markTestIncomplete('Not implemented yet.');
Why does it mark as incomplete? We can implement a basic test here. Same for others test methods.

2020-01-03 10:30 UTC, batopa commented on plugins/BEdita/Core/src/Model/Behavior/CategoriesBehavior.php
> +                    ->getAssociation('ObjectTypes')
too much indentation here

2020-01-07 10:22 UTC, stefanorosanelli commented on plugins/BEdita/Core/tests/TestCase/Model/Behavior/CategoriesBehaviorTest.php
> +     * Test correct save of custom properties.
Probably :)

2020-01-07 10:54 UTC, stefanorosanelli commented on plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectCategoriesTableTest.php
> +        $this->markTestIncomplete('Not implemented yet.');
That's true, however for similar table classes like `ObjectPermissionsTable` and `ObjectPropertiesTable` test cases are similar, with incomplete tests... 
I'll try to add one here

2020-01-07 11:24 UTC, stefanorosanelli commented on plugins/BEdita/Core/tests/TestCase/Model/Table/ObjectCategoriesTableTest.php
> +        $this->markTestIncomplete('Not implemented yet.');
done

2020-01-07 11:36 UTC, stefanorosanelli commented
> I think a better implementation could be done having two Tables and Entities i.e. `CategoriesTable`, `TagsTable`, `Category` and `Tag`.

I agree, didn't think it this way because we normally have a single table class for a db `resource` type table. But it makes sense, especially for future uses of the table classes.

I'll try to implement this refactor, if too problematic will decide how to proceed.

2020-01-09 10:52 UTC, batopa approved these changes

2020-01-09 16:29 UTC, merged