Issue/v4/1654 default priority
bedita/bedita pull request #1659
Opened 2020-02-21 10:56 UTC by stefanorosanelli

This PR fixes #\<issue-number\>

2020-02-25 16:58 UTC, batopa requested changes

2020-02-25 16:58 UTC, batopa commented on plugins/BEdita/Core/src/Model/Table/ObjectRelationsTable.php
> +use Cake\Datasource\EntityInterface;
unused `use` statements

2020-02-25 17:32 UTC, stefanorosanelli commented on plugins/BEdita/Core/src/Model/Table/ObjectRelationsTable.php
> +use Cake\Datasource\EntityInterface;
done

2020-02-26 07:57 UTC, batopa approved these changes

2020-02-26 07:58 UTC, merged