Issue/v4/1551 images upload
bedita/bedita pull request #1673
Opened 2020-04-05 18:33 UTC by stefanorosanelli

This PR fixes #1551

2020-04-16 08:47 UTC, batopa requested changes

2020-04-16 08:47 UTC, batopa commented on plugins/BEdita/API/src/Controller/UploadController.php
> +        $this->Upload->upload($fileName, $objectId);
I think these operations should stay in a transaction.

2020-04-20 08:45 UTC, batopa approved these changes

2020-04-21 08:08 UTC, didoda approved these changes

2020-04-21 08:42 UTC, merged