WIP: Links
bedita/bedita pull request #1684
Opened 2020-04-29 05:53 UTC by didoda

This PR fixes #1683 
Adding:

 - migration for links table
 - link entity
 - links table
 - basic tests

2020-04-29 06:31 UTC, stefanorosanelli requested changes

2020-04-29 06:31 UTC, stefanorosanelli commented on plugins/BEdita/Core/config/Migrations/20200429070603_LinksTable.php
> +            ->addColumn('http_status', 'string', [
`'url'`(or `uri`) field is missing?

2020-04-29 06:31 UTC, stefanorosanelli commented on plugins/BEdita/Core/config/Migrations/20200429070603_LinksTable.php
> +                        ],
add also:
```
'core_type' => 1,
'enabled' => 0,
```

2020-04-29 06:36 UTC, didoda commented on plugins/BEdita/Core/config/Migrations/20200429070603_LinksTable.php
> +            ->addColumn('http_status', 'string', [
yes... coming soon

2020-05-04 07:22 UTC, stefanorosanelli approved these changes

2020-05-04 07:22 UTC, stefanorosanelli commented on plugins/BEdita/Core/config/Migrations/20200429070603_LinksTable.php
> +            ->addColumn('last_update', 'date', [
`timestamp` or `datetime` maybe better

2020-05-04 11:08 UTC, merged