Clone endpoint
bedita/bedita pull request #2117
Opened 2024-11-26 15:43 UTC by didoda

This provides #2017

2024-11-29 18:09 UTC, batopa requested changes

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/API/src/Controller/ObjectsController.php
> +        return null;
I would respond with a `201 Created` with `Location` header containing the url of the new object.

```php
$this->response = $this->response
    ->withStatus(201)
    ->withHeader('Location', $this->resourceUrl($entity, 'id'));
```
 We can also set `:void` in returned type signature of the method

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/API/tests/TestCase/Controller/ObjectsControllerTest.php
> +        static::assertSame('test', $result['data']['attributes']['title']);
After the modify to `ObjecstController::clone()` method we should test `201` status code and `Location` header.
Moreover we could test the id of the new object getting the last inserted before the POST request

```php
$lastObjectId = $this->lastObjectId();
// POST clone here
static::assertGreaterThan($lastObjectId, $result['data']['id']);
```

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        $this->authorId = empty(LoggedUser::id()) ? LoggedUser::getUserAdmin()['id'] : LoggedUser::id();
I think that the clone action should be done only if a user is logged. I would avoid to force the user admin here.
The `\BEdita\Core\Model\Behavior\UserModifiedBehavior` should take care of that and if there isn't any logged user it is correct that an error happens.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        $entity->set('modified_by', $this->authorId);
To remove, see the consideration about author id.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        return $entity;
```suggestion
        return $this->Table->getConnection()->transactional(function () use ($sourceId, $attributes, $include) {
            $objectType = $this->Table->objectType();
            $options = $objectType->hasAssoc('Streams') ? ['contain' => ['Streams']] : [];
            $source = $this->Table->get($sourceId, $options);
            $entity = $this->cloneEntity($source, $attributes);
            if (!empty($source->get('streams'))) {
                $this->cloneStreams($source->get('streams'), $entity);
            }
            if (in_array('relationships', $include)) {
                $this->cloneRelationships($sourceId, $entity->id);
            }
            if (in_array('translations', $include)) {
                $this->cloneTranslations($sourceId, $entity->id);
            }
            
            return $entity;
        });
```

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +    protected function setEntityField(array $schemaInfo, ObjectEntity $sourceEntity, ObjectEntity &$entity, string $field)
```suggestion
    protected function setEntityField(array $schemaInfo, ObjectEntity $sourceEntity, ObjectEntity $entity, string $field)
```

Objects are always passed by reference.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        $clonedStream = $streamsTable->clone($streamsTable->get($stream->uuid));
```suggestion
        $clonedStream = $streamsTable->clone($stream);
```

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        $action(compact('entity', 'relatedEntities'));
```suggestion
       $clonedStream->set('object_id', $entity->id);
       $streamsTable->saveOrFail($clonedStream);
```

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +class CloneAction extends BaseAction
Since it refers to clone of BEdita objects  I would rename to `CloneObjectAction`.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        return $related;
```suggestion
        $objectRelations = $objectRelationsTable->find()->where(['left_id' => $sourceId])->toArray();
        if (empty($objectRelations)) {
            return [];
        }
        
        $objectRelations = array_map(function ($objectRelation) use ($destinationId) {
            $objectRelation->set('left_id', $destinationId);
            $objectRelation->setNew(true);

            return $objectRelation;
        }, $objectRelations);

        $objectRelationsTable->saveManyOrFail($objectRelations);

        return $related;
```

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        $objectRelations = $objectRelationsTable->find()->where(['left_id' => $sourceId]);
I think we have to do the same operation with `'right_id' => $sourceId` to take care of inverse relations i.e. where the source is at the right of a relation.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        return $translations;
```suggestion
        $objectTranslations = $translationsTable->find()->where(['object_id' => $sourceId])->toArray();
        if (empty($objectTranslations)) {
            return [];
        }

        $objectTranslations = array_map(function ($objectTranslation) use ($destinationId) {
            $objectTranslation->set('object_id', $destinationId);
            $objectTranslation->setNew(true);
            
            return $objectTranslation;
        }, $objectTranslations);
        
        $translationsTable->saveManyOrFail($translations);

        return $objectTranslations;
```

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Utility/Schema.php
> +namespace BEdita\Core\Utility;
Maybe it's better a namespace as `BEdita\Core\Database\Schema`

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Utility/Schema.php
> +class Schema
I would rename in `SchemaHelper` or similar.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Utility/Schema.php
> +            if ($constraint['type'] === 'primary' && count($constraint['columns']) === 1) {
:thinking: Maybe we can pass an option to filter by `columns === 1`. Sometimes can be useful to consider also the case of multiple columns.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +            $source = $this->Table->get($sourceId, $options);
I think we should use `GetObjectAction` because it already filters objects available i.e. not deleted or with status not readable.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +            $options = $objectType->hasAssoc('Streams') ? ['contain' => ['Streams']] : [];
What about other possible associations as `DateRanges`, `Captions`, `Categories`, etc... . Maybe we can find a way to clone those associations reading from `ObjectType::$associations` and execute operations based on the association type.

2024-11-29 18:09 UTC, batopa commented on plugins/BEdita/Core/src/Utility/Schema.php
> +            if ($constraint['type'] === 'unique' && count($constraint['columns']) === 1) {
:thinking: Maybe we can pass an options to filter by `columns === 1`. Sometimes can be useful to consider also this case.

2024-12-02 08:01 UTC, didoda commented on plugins/BEdita/Core/src/Utility/Schema.php
> +class Schema
`SchemaTools` could be fine. `SchemaHelper` makes me think it is a cake helper

2024-12-02 08:23 UTC, didoda commented on plugins/BEdita/Core/src/Model/Action/CloneAction.php
> +        return $entity;
this way the action returns void; it could be useful to make the action return the cloned entity

2024-12-03 10:26 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneObjectAction.php
> +            }
We can put it inside `cloneEntity()`

2024-12-03 10:26 UTC, batopa commented on plugins/BEdita/Core/src/Model/Action/CloneObjectAction.php
> +        }
We can do an `array_map` similar to `cloneRelationships()` changing `object_id` and setting the entity as new.

2024-12-03 10:26 UTC, batopa commented on plugins/BEdita/Core/src/Utility/SchemaTools.php
> +            }
Minor but we can simplify a little removing nested `if`

```suggestion
            if ($constraint['type'] !== 'primary') {
                continue;
            }
            
            if (empty($options['count']) || count($constraint['columns']) === $options['count']) {
                $fields = array_merge($fields, $constraint['columns']);
            }
```

2024-12-03 10:26 UTC, batopa commented on plugins/BEdita/Core/src/Utility/SchemaTools.php
> +            }
The same as for `getPrimaryFields()`.

2024-12-03 10:26 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Action/CloneObjectActionTest.php
> +        };
`CloneObjectAction::cloneRelationships()` is already public. Maybe it is changed the visibility during some refactoring.

2024-12-03 10:26 UTC, batopa commented on plugins/BEdita/Core/tests/TestCase/Model/Action/CloneObjectActionTest.php
> +        $this->expectException(\Cake\Http\Exception\UnauthorizedException::class);
[super minor] I would add `use` statement

2024-12-03 10:28 UTC, didoda commented on plugins/BEdita/Core/src/Model/Action/CloneObjectAction.php
> +            }
The function needs `$entity->id`, so we can't move it.

2024-12-03 10:56 UTC, batopa approved these changes

2024-12-03 11:21 UTC, merged